<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Product Details - {{ $product->name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 8px;
            margin-bottom: 30px;
        }

        .header h1 {
            margin: 0;
            font-size: 32px;
        }

        .header p {
            margin: 5px 0 0 0;
            font-size: 14px;
            opacity: 0.9;
        }

        .content {
            padding: 20px;
        }

        .detail-row {
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 1px solid #e5e7eb;
        }

        .detail-row:last-child {
            border-bottom: none;
        }

        .label {
            font-weight: bold;
            color: #667eea;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 5px;
        }

        .value {
            font-size: 18px;
            color: #1f2937;
            margin-top: 5px;
        }

        .price {
            font-size: 32px;
            font-weight: bold;
            color: #10b981;
        }

        .stock {
            display: inline-block;
            padding: 5px 15px;
            background: #dbeafe;
            color: #1e40af;
            border-radius: 20px;
            font-weight: bold;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
            padding-top: 20px;
            border-top: 2px solid #e5e7eb;
        }

        .meta-info {
            margin-top: 30px;
            padding: 15px;
            background: #f9fafb;
            border-radius: 8px;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ config('app.name', 'Laravel') }}</h1>
        <p>Product Details Report</p>
    </div>

    <div class="content">
        <div class="detail-row">
            <div class="label">Product ID</div>
            <div class="value">#{{ $product->id }}</div>
        </div>

        <div class="detail-row">
            <div class="label">Product Name</div>
            <div class="value">{{ $product->name }}</div>
        </div>

        <div class="detail-row">
            <div class="label">Description</div>
            <div class="value">{{ $product->description ?? 'No description available' }}</div>
        </div>

        <div class="detail-row">
            <div class="label">Price</div>
            <div class="price">${{ number_format($product->price, 2) }}</div>
        </div>

        <div class="detail-row">
            <div class="label">Stock Quantity</div>
            <div class="value">
                <span class="stock">{{ $product->stock }} units</span>
            </div>
        </div>

        <div class="meta-info">
            <strong>Report Information</strong><br>
            Generated on: {{ now()->format('F d, Y - h:i A') }}<br>
            Generated by: {{ auth()->user()->name }} ({{ auth()->user()->email }})
        </div>
    </div>

    <div class="footer">
        <p>&copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>
</body>

</html>
